name: build and publish

on:
  push:
    branches: [ develop ]

jobs:
  build-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github

      - name: Install xmllint tool
        shell: bash
        continue-on-error: true
        run: |
          sudo apt-get clean
          sudo apt-get install -f
          sudo dpkg --configure -a
          sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Extract snapshot version from pom.xml
        id: extractVersion
        run: |
          serviceVersion=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
          echo "serviceVersion=$serviceVersion"
          echo "serviceVersion=$serviceVersion" >> $GITHUB_OUTPUT

      - name: Check if version contains -SNAPSHOT
        run: |
          if [[ ${{ steps.extractVersion.outputs.serviceVersion }} != *-SNAPSHOT* ]]; then
          echo "Snapshot version must have suffix -SNAPSHOT"
          exit 1
          fi

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE }}

  delete-old-packages:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: com.blas.${{ github.event.repository.name }}
          package-type: maven
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE }}
